"""Functions to fetch and process data from the ECMWF WeatherBench dataset."""
from dateutil import parser
import gcsfs
import numpy as np
import pandas as pd
import xarray as xr
from nuthatch import cache
from nuthatch.processors import timeseries

from sheerwater.utils import dask_remote, get_variable, lon_base_change, regrid, shift_by_days
from sheerwater.interfaces import forecast as sheerwater_forecast, spatial


@dask_remote
@spatial()
@timeseries(timeseries=['init_time'])
@cache(cache=False,
       cache_args=['variable', 'prob_type', 'grid'],
       backend_kwargs={'chunking': {"lat": 300, "lon": 300, "prediction_timedelta": 10, "init_time": 25}})
def cumulus_ai_raw(start_time, end_time, variable='precip', prob_type='deterministic',  # noqa: ARG001
                version='v0.0.0',
                grid="global1_0", mask=None, region='global'):  # noqa: ARG001
    """Fetches Cumulus AI model from our cloud."""
    def add_lead(ds):
        """Preprocess to add lead time and proper time from filename."""
        ff = ds.encoding["source"]
        # Example: '/Users/mudflat/content/cumulus-data/v0.0.0/data/2016-08-13-00-0096.nc'
        fname = ff.split('/')[-1]
        # Extract datetime part and lead hour part
        # Expected fname: '2016-08-13-00-0096.nc'
        # Here, we do not need the fuzzy argument – the string is clear and well-formatted
        time_part = "-".join(fname.split('-')[:3])  # '2016-08-13-00-0096' -> '2016-08-13'
        dt = parser.parse(time_part)
        # Extract lead hour (before .nc, after last '-')
        lead_hr_str = fname.split('-')[-1].replace('.nc', '')  # '0096'
        try:
            lead_hr = int(lead_hr_str)
        except Exception:
            raise ValueError(f"Failed to parse lead hour from filename: {fname}")
        ds = ds.expand_dims(dim='time') if 'time' not in ds.dims else ds
        ds = ds.assign_coords(time=[dt])
        ds = ds.expand_dims(dim='prediction_timedelta') if 'prediction_timedelta' not in ds.dims else ds
        ds = ds.assign_coords(prediction_timedelta=[np.timedelta64(lead_hr, 'h').astype('timedelta64[ns]')])
        return ds

    # This is coming from forecasts generated by the UChicago team that I
    # copied into our bucket
    fs = gcsfs.GCSFileSystem(project='sheerwater', token='google_default')
    gsf = ['gs://' + x for x in fs.ls(f'gs://sheerwater-datalake/cumulus-data/{version}/data')]
    ds = xr.open_mfdataset(gsf, engine='h5netcdf', preprocess=add_lead, parallel=True)

    ds = ds.rename({'latitude': 'lat', 'longitude': 'lon', 'time': 'init_time'})

    # Convert to base180 longitude
    ds = lon_base_change(ds, to_base="base180")
    ds = ds.sortby('lat', ascending=True)

    # Select the right variable
    var = get_variable(variable, 'cumulus_ai')
    ds = ds[[var]]

    # Fix up prediction_timedelta by subtracting one day, since they index at day 0 = 24 hrs
    ds['prediction_timedelta'] = ds['prediction_timedelta'] - np.timedelta64(1, 'D')

    # Perform variable renaming if a variable is reuqested
    variable = get_variable(var, 'sheerwater')
    ds = ds.rename_vars(name_dict={var: variable})

    # Perform unit conversions if a specific variable is requested
    if variable == 'precip':
        # Already in mm
        ds[variable] = np.maximum(ds[variable], 0)

    # Average the member if necessary
    if prob_type != 'deterministic':
        raise ValueError("Only deterministic cumulus_ai is supported.")

    # Regrid if necessary
    if grid == 'global1_0':
        pass
    else:
        ds = regrid(ds, grid, base='base180', method='conservative')

    return ds


@dask_remote
@sheerwater_forecast()
@cache(cache=False,
       cache_args=['variable', 'agg_days', 'event', 'event_kwargs', 'processors', 'processor_kwargs',
                   'lookback_source', 'densify',
                   'prob_type', 'grid', 'mask', 'region'],
       backend_kwargs={'chunking': {'lat': 300, 'lon': 300, 'time': 365, 'lead_time': 1, 'member': 1}})
def ecmwf_aifs(start_time=None, end_time=None, variable="precip", agg_days=1, prob_type='deterministic',  # noqa: ARG001
               event=None, event_kwargs=None,  # noqa: ARG001
               processors=None, processor_kwargs=None,  # noqa: ARG001
               lookback_source=None, densify=False,  # noqa: ARG001
               grid='global0_25', mask='lsm', region="global"):
    """Standard format forecast data for ECMWF forecasts."""
    forecast_start = shift_by_days(start_time, -46) if start_time is not None else None
    ds = cumulus_ai_raw(start_time=forecast_start, end_time=end_time, variable=variable,
                        prob_type=prob_type,
                        grid=grid, mask=mask, region=region)

    if prob_type == 'deterministic':
        ds = ds.assign_attrs(prob_type=prob_type)
    else:
        raise ValueError("Only supports deterministic forecasts")

    return ds
